### ISSUE TITLE
import error...

### ISSUE THREAD

**Issue by thomgb** [LettError/glyphBrowser#1]
``` python
Traceback (most recent call last):
  File "browser.py", line 3, in <module>
ImportError: cannot import name unicodeToChar
```

**Comment by LettError** [comment]
RoboFont but not a beta?

**Comment by thomgb** [comment]
Normal RF 1.6

**Comment by LettError** [comment]
Should be fixed in 1.5 - can you check?

**Comment by thomgb** [comment]
Yes! Solved. Thanks Erik :)

I had the same idea a while ago. 
I made an Observer for when a new font opens this dialog pops up. I can selected the unicode ranges I want an fill the font family / style name. These glyphs are then added to the font. In the settings of RF the default character set is empty.

![screen shot 2016-02-29 at 13 15 32](https://cloud.githubusercontent.com/assets/1517937/13394193/14de9056-dee7-11e5-838b-14916d507167.png)

:)

**Comment by LettError** [comment]
Nice! I've thought about a column that shows

- if the glyph is present in the current font
- if the glyph in the list has the same unicode but a different name

Also: connect to glyphConstructions. But that might take a bit more work in the database.

**Comment by thomgb** [comment]
Some controle would be handy, how the glyphs are added if they already there (clear / do nothing / give a warning / mark / ...)

An other thing: if glyphs are added via your script they are already touched / dirty / unsaved. I do not like that. I think it would be better if they are added as clean templateGlyphs. My script does that.
Please take a look at my approach: https://github.com/thomgb/AddSetToFont

Like to hear your what you think. :)


About  glyphConstructions. I don't like to many databases in my workflow. I lose some overview sometimes, if a thing changes here in this database then I have to change it there also. That is not wise, I want to have one database. 
But adding glyphs is something different then drawing/checking/generating diacritics right? So I thinks a different db could work here just fine... 
How could the glyphConstructions work in this script, überhaupt?

**Comment by LettError** [comment]
Do the template glyphs retain their unicodes once they've been added to the UFO, then saved, closed, re-opened?

**Comment by thomgb** [comment]
Yes.
