### ISSUE TITLE
Worth updating to newer Unicode versions?

### ISSUE THREAD

**Issue by rbmntjs** [LettError/glyphBrowser#28]
I’m not sure how much manual work is involved in the naming scheme or the data management, but it’s a few years out now and I’m curious :)

**Comment by LettError** [comment]
Yes it is manual work. If you need specific things ask them here. If you need them in a hurry, PRs welcome!

**Comment by LettError** [comment]
Working on it:
https://github.com/LettError/glyphNameFormatter/pull/115/commits/d99c7a2be71e8bf014d486560726916f9542d980
