### ISSUE TITLE
Missing Greek letters from the glyphBrowser

### ISSUE THREAD

**Issue by thynem** [LettError/glyphBrowser#5]
Hello Erik, 
just to report on 6 missing letters from the Greek section, these are:

**/Beta /Chi /Omega /beta /chi /omega**

Attached an example screenshot, with the current version of glyphBrowser, showing the range of Uppercase and the missing glyphs.

<img width="1198" alt="screen shot 2017-10-11 at 21 19 39" src="https://user-images.githubusercontent.com/23339296/31461972-5599036e-aecb-11e7-9f1f-ae8c5c0e391d.png">

**Comment by LettError** [comment]
Hi @thynem, sorry I missed your report. I made some other changes to the Greek earlier today, but not this. I'll look.

**Comment by LettError** [comment]
Fixed.
