### ISSUE TITLE
Traceback in py3

### ISSUE THREAD

**Issue by LettError** [LettError/glyphBrowser#7]
I could use a suggestion on solving this one. When typing something in the search box:

https://github.com/LettError/glyphBrowser/blob/fb95cb40cb619eebe9557e986d9ef97db6327480/GlyphBrowser.roboFontExt/lib/browser.py#L758

```TypeError: '<' not supported between instances of 'SimpleGlyphName' and 'SimpleGlyphName'```

**Comment by typemytype** [comment]
you will need to touch the version number yourself
this will set Mechanic in motion
